[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "rm -rf .next node_modules package-lock.json && npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NODE_VERSION = "22"

[[plugins]]
  package = "@netlify/plugin-nextjs"
